import './scripts/clients-slider.js'
import './scripts/totop-button.js'
import './scripts/provide-slider.js'
import './scripts/connection-spoiler.js'
import './scripts/burger-menu.js'
import './styles/index.scss'
import './index.pug'
